name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dev-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        cd services/web      # change to the folder containing requirements.txt
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Start Flask dev server
      run: |
        cd services/web
        nohup python manage.py run -p 1105 &
        sleep 5

    - name: Check dev server
      run: |
        curl --fail http://127.0.0.1:1105 || exit 1

    - name: Stop dev server
      run: |
        pkill -f "python manage.py run"
